Question 1:

Write a program that calculates and prints the value according to the given formula:

Q = Square root of [(2 * C * D)/H]

Following are the fixed values of C and H:

C is 50. H is 30.

D is the variable whose values should be input to your program in a comma-separated sequence.

Example

Let us assume the following comma separated input sequence is given to the program:

100,150,180

The output of the program should be:

18,22,24


In [19]:
import math
def calculate_sq(a,b,c):
    l1=[a,b,c]
    l2=list()
    C=50
    H=30
    for D in l1:
        temp=(2*C*D)/H
        Q=math.sqrt(temp)
        Q=int(Q)
        l2.append(Q)
    return l2
a,b,c=input("Enter Three values separated by comma, : ").split(",")
a=int(a)
b=int(b)
c=int(c)
calculate_sq(a,b,c)

Enter Three values separated by comma, : 100,150,180


[18, 22, 24]

Question 2:
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.

Note: i=0,1.., X-1; j=0,1,¡¬Y-1.

Example

Suppose the following inputs are given to the program:

3,5

Then, the output of the program should be:

[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]] 



In [32]:
import numpy as np
x=int(input("Enter the row size of the 2D array"))
y=int(input("Enter the column size of the 2D array"))
print("Enter the value in row wise")
entries=list(map(int, input().split()))
matrix=np.array(entries).reshape(x,y)
print(matrix)

Enter the row size of the 2D array3
Enter the column size of the 2D array4
Enter the value in row wise
1 2 5 4 5 6 7 8 9 1 5 9
[[1 2 5 4]
 [5 6 7 8]
 [9 1 5 9]]


Question 3:
Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.

Suppose the following input is supplied to the program:

without,hello,bag,world

Then, the output should be:

bag,hello,without,world


In [44]:
wordlist=list(map(str,input("Enter Three values separated by comma, : ").split(",")))
word_res=sorted(wordlist)
" ,".join(word_res)

Enter Three values separated by comma, : without,hello,bag,world


'bag ,hello ,without ,world'

Question 4:
Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

Suppose the following input is supplied to the program:

hello world and practice makes perfect and hello world again

Then, the output should be:

again and hello makes perfect practice world


In [48]:
wordlist=list(map(str,input("Enter your strings with separated whitespace, : ").split()))
word_res=set(wordlist)
output=list(sorted(word_res))
" ".join(output)

Enter your strings with separated whitespace, : hello world and practice makes perfect and hello world again


'again and hello makes perfect practice world'

Question 5:
Write a program that accepts a sentence and calculate the number of letters and digits.

Suppose the following input is supplied to the program:

hello world! 123

Then, the output should be:

LETTERS 10

DIGITS 3


In [58]:
wordlist=list(map(str,input("Enter your strings with separated whitespace, : ").split()))
letter=0
digit=0
for i in range(len(wordlist)):
    if wordlist[i].isalpha()==True:
        letter=letter+len(wordlist[i])
    elif wordlist[i].isdigit()==True:
        digit=digit+len(wordlist[i])
print(f"Number of letters : {letter}")
print(f"Number of digits : {digit}")
    

Enter your strings with separated whitespace, : hello world ! 123
Number of letters : 10
Number of digits : 3


Question 6:
A website requires the users to input username and password to register. Write a program to check the validity of password input by users.

Following are the criteria for checking the password:

1. At least 1 letter between [a-z]

2. At least 1 number between [0-9]

1. At least 1 letter between [A-Z]

3. At least 1 character from [$#@]

4. Minimum length of transaction password: 6

5. Maximum length of transaction password: 12

Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma.

Example

If the following passwords are given as input to the program:

ABd1234@1,a F1#,2w3E*,2We3345

Then, the output of the program should be:

ABd1234@1


In [4]:
import re
def pswd_check(pswd):
    if re.fullmatch('(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!#%*?&]{6,12}',pswd):
        return True
    else:
        return False
mylist=list(map(str,input("Enter Three values separated by comma, : ").split(",")))
for pswd in mylist:
    if(pswd_check(pswd))==True:
        print(f"The {pswd} is Valid")
    else:
        print(f"The {pswd} is Invalid")


Enter Three values separated by comma, : ABd1234@1,a F1#,2w3E*,2We3345
The ABd1234@1 is Valid
The a F1# is Invalid
The 2w3E* is Invalid
The 2We3345 is Invalid
